### ISSUE TITLE
Realtime link on apache web interface  reports Error via popup

### ISSUE THREAD

**Issue by BlackSpruce** [Matthias-Wandel/imgcomp#12]
Great software btw. 
One minor issue so far; after activating the Web interface , I then click on the "Realtime" link and get a popup message saying "Error! No log.txt file"
The photo does appear after dismissing the popup.
Browser is Firefox v 77 on windows 10. Raspberry Pi  model 3 model B.

Regards,
Peter

**Comment by Matthias-Wandel** [comment]
You need to have the logs created, in the config file for that to work.
