### ISSUE TITLE
/ramdisk/out00394.jpg: No such file or directory

### ISSUE THREAD

**Issue by hellobritt** [Matthias-Wandel/imgcomp#14]
I was able to get imgcomp working and writing images. I rebooted my pi and now when i run `$ imgcom/imgcomp` i get an error `/ramdisk/out00394.jpg: No such file or directory`

**Comment by hellobritt** [comment]
I can see new images in the web interface, but I still get the ramdisk error when I run `imgcom/imgcomp`.

**Comment by Matthias-Wandel** [comment]
What is producing this message?
What are the permissions of that file?
Is it always the same file?



------ Original Message ------

**Comment by Matthias-Wandel** [comment]
Do not run imgcomp/imgcomp if you already have a copy running.
When running the setup scripts, it sets it up to start automatically at 
startup.
If you don't want that, run "crontab -e" and remove the lines that start 
it.

------ Original Message ------
