### ISSUE TITLE
Delete directory function from browser

### ISSUE THREAD

**Issue by jmd1979** [Matthias-Wandel/imgcomp#15]
Hi,
Just a suggestion here. It would be convenient to have the ability to delete image directories from the browser. I’ve looked at the browsing source code, but I’m just not proficient enough in c to modify the code to add the functionality.

**Comment by Matthias-Wandel** [comment]
Not planning on implementing this.

**Comment by lukepighetti** [comment]
If you want look super cool on github label this as `wontfix` 😄
