### ISSUE TITLE
Option to use Nginx 

### ISSUE THREAD

**Issue by Pi-DD** [Matthias-Wandel/imgcomp#16]
It would be nice to have this as an option for those already using it to save the complexity of running two web servers. 

PS - as a long time MotionEye user - I like this a lot Matthias, particularly your “actagram”!

**Comment by Matthias-Wandel** [comment]
What needs to be done to run a CGI program from ngix?  I have no 
familiarity with ngix.

------ Original Message ------

**Comment by Pi-DD** [comment]
Hello Matthias ! Your very swift response has forced me to go educate myself a bit more about this - that is how one learns! 
It seems the “issue” I had not understood is that Nginx goes not readily accommodate cgi based programming. It can, but doing so is not elegant!
The reason for my suggestion was that I try to keep everything simple (given my limited technical skills!) and that motivated me to think a single web server a “better” idea. 
From what I have now learned there is a quite simple way of dealing with this (which, as it happens I know how to do!). 
That is to leave your solution running in Apache and simply access it via a reverse proxy in Nginx that is invoked for all cgi scripts or just for your software. 
For that to work best it would be helpful if your use of apache could easily be configured to use an unusual port (which MotionEye does incidentally, using 8765) so that there is no risk of a conflict if Nginx is already using common ports to provide its web site. 


PS - it would be interesting to see your software running in an environment with very variable lighting conditions, such as outside. That often produces a lot of false positives.

**Comment by Matthias-Wandel** [comment]
motioneyes by default uses port 80 (I played around with it)
If you want apache to be on a different port, just configure apache to 
be on a different port.
Making my software configure it to a non standard port would be 
confusing to almost everyone, so counterproductive.

------ Original Message ------

**Comment by lukepighetti** [comment]
Seeing as this is a very opinionated piece of software I think that leaving it bundled with whatever the creator uses personally (apache) makes sense. Very little value add, especially considering the complexity added, to support other web servers.

**Comment by Pi-DD** [comment]
> motioneyes by default uses port 80 (I played around with it) If you want apache to be on a different port, just configure apache to be on a different port. Making my software configure it to a non standard port would be confusing to almost everyone, so counterproductive.
> […](#)

Port 80 - True for MotionEyeOS, but not for MotionEye running under chosen Linux, that uses 8765 for access to web interface and port of your choice to stream separately. 

Agree, it doesn’t make sense to add complexity to what you have created by messing with other web servers, given there is a perfectly simple way around it. 

I have a couple of spare Pi’s with cameras- some I’ll look on this as a learning exercise for Apache as well as trying out your nice application!
