### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Matthias-Wandel/imgcomp#18]
Would you like to add more error handling for return values from functions like the following?
- [fopen](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream.") ⇒ [ShowLatestJpg](https://github.com/Matthias-Wandel/imgcomp/blob/855ffac43181b99abd8410c049b43e4703dcac1e/browse/view.c#L293)
- [ftell](https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "Return a file offset.") ⇒ [main](https://github.com/Matthias-Wandel/imgcomp/blob/855ffac43181b99abd8410c049b43e4703dcac1e/browse/wait_change.c#L119)

**Comment by Matthias-Wandel** [comment]
What does it matter whether I like to.  It’s a matter of need to and
available time.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by Matthias-Wandel** [comment]
What does it. After what I think.  I don’t have the time.
