### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Matthias-Wandel/imgcomp#2]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [closedir](https://github.com/Matthias-Wandel/imgcomp/blob/9044f133c7f4baeaafb49773875b9ff4edb35afb/src/dir_win.c#L106 "closedir function")
- [ProcessImage](https://github.com/Matthias-Wandel/imgcomp/blob/a003c984005d203a583aaa3ab1b1c2380d4074f6/src/main.c#L238 "ProcessImage function")

**Comment by Matthias-Wandel** [comment]
Feel free to make those changes and I'll take them.

------ Original Message ------
