### ISSUE TITLE
fstab null chartacters

### ISSUE THREAD

**Issue by jeanpaulmiller** [Matthias-Wandel/imgcomp#20]
Using latest raspberry os lite fully apt-get updated . The tree statement that appends the ramdisk into the fstab put a series of null characters (^@ in vi) preceding the line.. had to manually remove to get mount to understand fstab.  

I do not see any overt problem with the tee command. Not sure why it is happening. easy enough post break fix if you use an editor that can see null characters.

**Comment by Matthias-Wandel** [comment]
Have not seen this happening, or at leaset, if there are null characters, it has not had any effect.

**Comment by ryanmccool** [comment]
@Matthias-Wandel not sure if this is related or not, but i successfully installed imgcomp on one model 3 RasPi (thank you by the way, great application). Just now, as I tried to install it on a fresh RasPi Zero, I can see it capture images into the proper directory, but realtime mode and the JS view mode don't render properly.

Furthermore, I ran the program while ssh'd into the zero and ran imgcomp from CLI and when trying to access JS View from a browser, it errored out w/ "/ramdisk/out00389.jpg: No such file or directory".

Related, or different problem?

**Comment by jeanpaulmiller** [comment]
After some thought I know I localized my pi off of en-GB.  I assume it has to do with character set compatibility with utf8 and the tee command in setup-imgcomp-root but if that is the case the error is with tee not with imgcomp scripts. Someone out there might know tee better then me though.

You can check if it is the same error in this way:

You can try to mount the ram disk manually by cutting and pasting the mount line out of the script setup-imgcomp-root. If you use the script, it might absorb the errors and you will be left knowing nothing new. When run outside the script if it is the same problem it will  give an error that says something like: "unknown character line: 5" or some such message.

If this is the case you can open up the /etc/fstab file and seeing if there are extra characters in front of the line making the ram disk mount.  vi and emacs should show the characters your mileage may vary with newer notepad like editors (pico nano joe).

It is an easy fix just remove the extra characters. 

Many of the older file formats, notably makefiles and a few 'relics' in the etc directory, are VERY picky about white-spaces and unknown characters.

**Comment by ryanmccool** [comment]
Thanks @jeanpaulmiller. No errors when mounting the ramdisk, so my issue must lie elsewhere. 

I feel like it is related to the web server and HTML / cgi app. When I visit the www folder, I see view.cgi but do not see realtime.html or some other files. See screenshot for details. I welcome any tips on how to fix this; in the meantime, I’ll start from scratch and see how it ends up and then continue to troubleshoot.

![24E8DADD-7C7E-4FB3-B2E4-6EAF0EF76B2D](https://user-images.githubusercontent.com/1365935/86298499-7db12680-bbc3-11ea-9a9f-1b98099c7c71.jpeg)

Post edit - digging through setup scripts, I don’t know that those <missing> files were ever there (or supposed to be there) to begin with. I’ll do some comparative analysis against my working RasPi.

Also, I guess we can close this issue since it likely isn’t relevant any longer.

**Comment by Matthias-Wandel** [comment]
Do NOT run more than one instance of imgcomp.
After installing it, it will start automatically.  If you want to start 
an instance from command line, please make sure the previous instance is 
killed first.

------ Original Message ------

**Comment by Matthias-Wandel** [comment]
I need to see what ouput the makefile in the browse directory produces.
so go into the imgcomp/browse directory
and type make

I don't know why the copy command did not run on your pi.  I really 
can't diagnose this from here without extra info.

------ Original Message ------

**Comment by Matthias-Wandel** [comment]
I eliminated the use of 'tee" in change e3d49b14...
This should fix the problem.  As for the other problem you reported, that is a separate, unknown issue, that is a separate issue, not THIS issue..  I will close this one, as this should address the issue that this issue is about.
