### ISSUE TITLE
Issues with new Actagram in Safari

### ISSUE THREAD

**Issue by bcdc13** [Matthias-Wandel/imgcomp#21]
Just an FYI.  The new canvas method that was merged in earlier today breaks in Safari.  The entire histogram just doesn't show at all.

**Comment by fairclothjm** [comment]
@bcdc13 

works for me in Safari `Version 13.1.1 (15609.2.9.1.2)`

What version are you running? Are there any console errors?

**Comment by fairclothjm** [comment]
@bcdc13 

Can you pull this branch and check if you see the same behavior?

https://github.com/fairclothjm/imgcomp/tree/actagram-stripes

**Comment by Matthias-Wandel** [comment]
Try rreloading the page (sometimes the old HTML is cached)
Works fine on safari on my iPad.

------ Original Message ------

**Comment by bcdc13** [comment]
Turns out I didn’t fully uninstall the app. Removing the imgcomp dir wasn’t enough. The setup scripts weren’t overwriting the files in www. After removing everything and re-cloning the repo things worked.
