### ISSUE TITLE
alert feature

### ISSUE THREAD

**Issue by fairclothjm** [Matthias-Wandel/imgcomp#29]
Matthias,

Would you be interested in an alert feature for imgcomp?

I have a working prototype and I am wondering if you would be interested. The basic design is as follows:

- on startup read alert program configuration from `imgcomp.conf`
  - `<alert_program> <flags>`
  - `mail.alert -s "alert subject" -r recipient@email.com`
- when an image is flagged to be saved to disk
- call external alert program, passing the path to the image
- external alert program emails the image to address defined in config

The external alert program doesn't have to be limited to email. Alternative alert programs could be written to do other things, since the alert program and its flags are user-defined in the config and passed along from imgcomp. For example, other alert programs could upload the image to an external server (`scp.alert`) or send the image via text message (`text.alert`).

**Comment by Matthias-Wandel** [comment]
I had the program call something on images, the blink led program.  Also
have it send Udp packets on changes.  Email is probably inappropriate,as
any actual event results in typically about 10 images, so 10 emails is a
bit much.
But having it notify an external program would be good, and that external
program could decide what to do, such as emailing maybe.  But imgcomp
doesn’t need to know what email address the other program would mail to if
it does.

**Comment by fairclothjm** [comment]
ok, thanks for the feedback
