### ISSUE TITLE
view.cgi not showing enlarged images

### ISSUE THREAD

**Issue by ckortenhorst** [Matthias-Wandel/imgcomp#31]
I did git pull for imgcomp and everything works excluding when I try to enlarge an image I get no image yet the image is there /view.cgi?201013/16/#1013-160000%200031.jpg 

![image](https://user-images.githubusercontent.com/5760635/95878936-b1c4e780-0d6d-11eb-977e-3896388079c5.png)

Any thoughts?

**Comment by Matthias-Wandel** [comment]
Javascript is failing on your computer somehow.
I'd have to know more about what you are doing to figure this out.  Like 
what os/browser.
Javascript console output would help to narrow it down.

Matthias

------ Original Message ------

**Comment by ckortenhorst** [comment]
Firefox working fine, chrome not working on os x 

![image](https://user-images.githubusercontent.com/5760635/95880890-e8036680-0d6f-11eb-9224-ba8fedf275f0.png)

![image](https://user-images.githubusercontent.com/5760635/95880944-f3ef2880-0d6f-11eb-8e44-76fb2132f365.png)

![image](https://user-images.githubusercontent.com/5760635/95880972-fa7da000-0d6f-11eb-9af0-bf3346cd5b7f.png)

**Comment by fairclothjm** [comment]
@ckortenhorst 

That is old code as you can see from the current code in showpic.js: https://github.com/Matthias-Wandel/imgcomp/blob/master/browse/showpic.js#L289

After git pull you will need to recompile.

```
$ cd ~/imgcomp/browse
$ make
```

If you have already done that, then Chrome is caching old content.

**Comment by ckortenhorst** [comment]
That is exactly it cached after upgrade. 

Thanks I love the app built these to monitor house build https://www.tog.ie/2020/06/raspberry-pi-outdoor-camera/

**Comment by Matthias-Wandel** [comment]
Thanks michael for taking care of this one.
