### ISSUE TITLE
Seeing Variable error in showpic.js

### ISSUE THREAD

**Issue by mrbc42** [Matthias-Wandel/imgcomp#32]
---
Pi3b+
current pi OS (Buster) updated
---

After upgrade to current version, getting the below error and showpic.js is not displaying image.  typed "make" in /imgcomp/browse as per above issue which solved bargraph not appearing.  Problem in Firefox and chrome on Debian Buster, Windows chrome and FF also

any ideas?

`Uncaught ReferenceError: ShwH is not defined
    PicMouse http://192.168.5.33/showpic.js:220
    picMouseMove http://192.168.5.33/showpic.js:347`

**Comment by Matthias-Wandel** [comment]
Can you tell me about the error?  The URLs you posted are local to your 
network, so I can't look at them.
Possibly hitting "reload" on the page may fix it.  But without knowing 
specifics of the error, I can't address it.

------ Original Message ------

**Comment by mrbc42** [comment]
Not sure what more info I can give, do you want to see something in particular?  
The way I did my upgrade is to 

- rename imgcomp to imgcomp.old 

- then git clone https://github.com/Matthias-Wandel/imgcomp.git

- then follow setting_up.txt

I could not see the bar graph so typed "make" in ./imgcomp/browse as described in the issue described by ckortenhorst which fixed part of the problem.

I have cleared the cache and cookies from the browser, clicked refresh, tried in a "private browsing" window, still the same.

If you dont have any more suggestions, maybe I will format and reinstall from scratch.
appreciate the help


![jsnotworking](https://user-images.githubusercontent.com/6986403/99788599-6de7ae00-2b75-11eb-8b85-56bbd3af36e4.png)

**Comment by fairclothjm** [comment]
@mrbc42  Hello

> The way I did my upgrade is to

> rename imgcomp to imgcomp.old

> then git clone https://github.com/Matthias-Wandel/imgcomp.git

> then follow setting_up.txt

The fact that you ran the setup scripts multiple times is most likely your problem. 

Can you provide the output from the following command?
```
ls -la /home/pi/www/pix
```

You should see something like this:
```
lrwxrwxrwx 1 pi pi 9 Aug 18 19:56 /home/pi/www/pix -> ../images
```

In the future, to update the code you can simply run the following commands
```
cd ~/imgcomp
git pull
make && cd browse && make
```

No need to re-clone the repo. Hope that helps

**Comment by mrbc42** [comment]
Thanks, the upgrade instructions were handy and ls -al looks exactly like yours.

I have more understanding of the problem now, I reformatted and started again.  Stock install worked and then I added my windows share for storing the images (freenas) and the problem reappeared.

added the following to the /etc/fstab
`//192.168.5.204/imgcomp/ /home/pi/images cifs defaults,uid=pi,gid=pi,user=pigarage,password=password,rw 0 0`

Its worth noting that all other aspects of the application work fine, thumbnails, actagram, capture (writing to the Freenas share).  Only thing not working is the viewing of the images.

not sure if this is sheds any new light or ideas, continuing to troubleshoot.

**Comment by fairclothjm** [comment]
I think the issue might be with your `/etc/fstab` entry. This part:
```
uid=pi,gid=pi
```

I think you need the actual `uid` and `gid` for the pi user. You can get these with the following command:
```
echo "id=$(uid -u pi),gid=$(id -g pi)"
```

which for me prints:
```
uid=1000,gid=1000
```

**Comment by toothrobber** [comment]
Hello 

# images from imagecomp  (fat)
#/dev/sdb1 /home/pi/images auto users,auto,sync,rw,dmask=027,fmask=137 0 0
UUID=848A-16FE       /home/pi/images   vfat   users,auto,sync,uid=1000,gid=1000,rw,dmask=022,fmask=133,noatime 0 0


This is what I use to mount the image directory

Robert

**Comment by mrbc42** [comment]
Tried the above and still the same :-(

More testing, 
Created a text file in ./images and can read and write to it from the console.  When accessing through the web brower, the text file comes out with Jibberish added rather than just plain text.

```
Console output:

this is a test to see if I can write to the share

```


```
Browser Output:

20 21:08:10 GMT
ETag: "33-5b4a45bbe8a7a"
Accept-Ranges: bytes
Content-Length: 51
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/plain

this is a test to see if I can write to the share

������������������ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ8üi¡Ÿjxbo?Ã:t™ÎèŸÂµë™ðÂoé¬qßÊºjRø˜–ÂbŠZ1ÍHÂŠ( Š( Š( f7‹!Ôâ# Û·ò¯‹§âWQØ

```

Tried to load a pic from the images dir through the browser and also got an error:
![Selection_001](https://user-images.githubusercontent.com/6986403/99888763-3a0aa680-2ca3-11eb-990c-d8f5e09c1160.png)

- Loading the same image through the network share renders fine
- Copied a known image from the desktop to the network share and tried to load through the browser, same error as above
- all images render fine from the network share even after loading through the browser so the errors are not permanently written to the file.

Something to do with Apache corrupting files as they load and they are unable to be displayed?

Matt

**Comment by Matthias-Wandel** [comment]
Apache runs as a different user.
I set the setuid bit on the CGI scripts to change the user to Pi.

But whatever it is you are experiencing, it's an apache / file sharing / 
permission issues.  I recommend you talk to someone with expertise in 
those areas.  I don't have experise in that sort of thing.

------ Original Message ------

**Comment by mrbc42** [comment]
In the interest of closing this ticket, I didn't end up solving the problem with CIFS as it was taking too long.  Created a NFS share on the Freenas box and used that with the pi and it worked straight away.

- Definitely not a variable problem with showpic.js
- Definitely a file permissions issue with Freenas and the CIFS mount on the Pi that I spent way too long trying to (unsuccessfully) solve

thanks all for the help and the great software
