### ISSUE TITLE
multiple configurations

### ISSUE THREAD

**Issue by wile1411** [Matthias-Wandel/imgcomp#36]
Just wondering if there was a way to have multiple conf files? reason is to have one conf set up for daylight hours
example:
aquire_cmd = raspistill -q 20 -n -th none -p 1000,0,600,450 -w 1600 -h 1200 -o /ramdisk/out%05d.jpg -t 0 -tl 500

and then a different conf setup for nighttime image capture
aquire_cmd = raspistill -q 20 -n -th none -p 1000,0,600,450 -w 1600 -h 1200 -o /ramdisk/out%05d.jpg -t 0 -tl 3000 -ISO 800 -ss 3000000 -br 80 -co 100

My current work around was to terminate the existing daemon, copy over the conf with a nighttime template at a certain time, then do the reverse in the mornings.

**Comment by Matthias-Wandel** [comment]
You can specify where the configuration file is on the command line, i
think.

**Comment by wile1411** [comment]
Thank Matthias - I'll play around with ping-ponging between conf files and use different start up commands
