### ISSUE TITLE
aquire_cmd was not raspistill, not setting output or exposure settings /ramdisk/out00382.jpg: No such file or directory

### ISSUE THREAD

**Issue by owlonastick** [Matthias-Wandel/imgcomp#41]
I've just done a fresh install on a raspberry 4 and gone through the imgcomp installation process with no errors that I noticed.

When I actually run it, I get the error shown in the title, i.e., this:

**aquire_cmd was not raspistill, not setting output or exposure settings
/ramdisk/out00382.jpg: No such file or directory**

The first bit of text that imgcomp displays to the screen is the following:

> Imgcomp version 1.01 (Jun 2023) by Matthias Wandel
> 
> Configuration parameters:
>     'aquire_cmd' = 'libcamera-still -v 0 -n --width 1600 --height 1200 -t 0 --timelapse 800 --quality 75 -o /ramdisk/out%05d.jpg'
>     'followdir' = '/ramdisk'
>     'spurious' = '1'
>     'brmonitor' = '0'
>     'savedir' = 'images'
>     'savenames' = '%y%m%d/%H/%m%d-%H%M%S'
>     'timelapse' = '1800'
>     'sensitivity' = '300'
>     'logtofile' = '/ramdisk/log.txt'
>     'movelognames' = 'images/%y%m%d/%H/Log.html'
>     Source directory = /ramdisk, follow=1
>     Save to dir images
>     Timelapse interval 1800 seconds
> fill 0-400,0-300
> Weight map (400x300):  '-' = ignore, '1' = normal, '#' = 2x weight

I've verified that libcamera-still is installed. And in fact, when I use the web browser to check on things, I can use the realtime button to see a live image; therefore, apparently the camera works and is configured correctly.

Can anyone offer any advice?

**Comment by Matthias-Wandel** [comment]
You have to use a config file that uses libcamera-still.

I shou look d switch the default, have not so far because radpistill works
better.

**Comment by owlonastick** [comment]
I used one of the example imgcomp.conf files. It contains this:

**# For frame rate of 1 fps or slower, use libcamera-still
aquire_cmd = libcamera-still -v 0 -n --width 1600 --height 1200 -t 0 --timelapse 800 --quality 75 -o /ramdisk/out%05d.jpg**

Is that not correct?

**Comment by owlonastick** [comment]
I did BTW rename it to 'imgcomp.conf' and didn't leave it named imgcomp.conf.example.

**Comment by Matthias-Wandel** [comment]
Yes use the line with libcamera still.  Go with the instructions in the
file.  I'm not at my computer so can't look at it in detail

**Comment by owlonastick** [comment]
I started over and reinstalled. Problem went away. So I'm closing this issue - since apparently there is no issue.
